# Generated by Django 4.2.2 on 2023-06-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=100)),
                ('cities', models.TextField()),
                ('links_on_cities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hospital', models.CharField(max_length=100)),
                ('number_phone', models.CharField(max_length=100)),
                ('awards', models.TextField()),
                ('overview', models.CharField(max_length=300)),
                ('ratings', models.CharField(max_length=100)),
                ('reviews', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cite', models.CharField(max_length=100)),
                ('links_on_hospital', models.TextField()),
            ],
        ),
    ]
