# Generated by Django 4.2.2 on 2023-06-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_remove_links_name_cite_alter_links_links_on_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='awards',
        ),
        migrations.AlterField(
            model_name='links',
            name='links_on_hospital',
            field=models.CharField(max_length=100),
        ),
    ]
