# Generated by Django 4.2.2 on 2023-06-29 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_remove_info_awards_alter_links_links_on_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='reviews',
            new_name='col_vo_reviews',
        ),
    ]
