# Generated by Django 4.2.2 on 2023-06-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_rename_reviews_info_col_vo_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='links_on_hospital',
            field=models.CharField(max_length=300),
        ),
    ]
